// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvfcdkrbfvtlebjbwvyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2ZmNka3JiZnZ0bGViamJ3dnljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MjAzNzAsImV4cCI6MjA2MTk5NjM3MH0.X9v5gUsgL0YYbglAcdaxY-jmdq_A7aWztEkQ-PaW8jo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});